### ISSUE TITLE
Can't update in platformio (Arduino nano)

### ISSUE THREAD

**Issue by rozrabiak** [RobTillaart/RS485#29] opened 2024-03-03 19:19 UTC
Hello Rob,
I can't update to latest version.
Info below:

![image](https://github.com/RobTillaart/RS485/assets/73905882/c2137dc7-c872-4efb-82d2-a42f3fcf5a76)

**Comment by RobTillaart** [comment] 2024-03-03 20:03
Have to look into that

**Comment by RobTillaart** [comment] 2024-03-03 20:10
version 0.5.0 is published
```
pio package publish
Preparing a package...
Type:     library
Owner:    robtillaart
Name:     RS485
Version:  0.5.0
Size:     13.88KB
UserSideException: The package `robtillaart/RS485@0.5.0` is already published in the registry
```

![image](https://github.com/RobTillaart/RS485/assets/462844/714acb26-ac4d-4127-898a-55077e2d2d28)

So it is published on platformio, even 4 versions more.

I do not know why you can't see the latest, 
maybe you need to update your platformio environment firrst?

(you can always fetch direct from GitHub...

**Comment by RobTillaart** [comment] 2024-03-10 13:44
@rozrabiak 
Did you find the cause yet ?  (for future reference)
As this is not a library issue you may close the issue

**Comment by RobTillaart** [comment] 2024-03-11 19:46
As this is not a library issue I close the issue, feel free to reopen if you have more information.

**Closed by RobTillaart** 2024-03-11 19:46 UTC
Labels: question
